# toggles
# emplement --root on every page, if true wont do anything if the file is empty
force-root=true

# leave empty if u dont wanna have a base
base="static/"

dirs {
    html="html/"
    css="css/"
    js="js/"
    img="img/"
}

defaults {
    root="defaults/title.html"
}

routes {
    html {
        # nothing before = means empty url basically index.html
        ="index.html"

        # /: means its a 404
        /:="defaults/404.html"

        #normal routes
        about="about.html"
        404="about.html"

    }
    css {
        index.css="index.css"
    }
    js {

    }
    img {
        favicon.ico="favicon.ico"
    }
}

api {
    /
}

MIME {
    .html="text/html"
    .css= "text/css"
    .js=  "application/javascript"
    .png= "image/png"
    .ico= "image/x-icon"
}