
base="static/"

dirs {
    html="html/"
    css="css/"
    js="js/"
    img="img/"
}

routes {
    html {
        contact="contact"
        about="about"
        map="map"
        languages="languages"
        talking="talking"
    }
    css {
        index.css="index.css"
    }
    js {

    }
}